apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice-container
          image: productservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090


